version: '3.1'
services:
  db:
    image: mdillon/postgis
    environment:
      POSTGRES_PASSWORD: synapsedb
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - 8080:8080
    links:
      - db
