"""empty message

Revision ID: 0a719c530811
Revises: b9f1fe4473a9
Create Date: 2018-05-29 17:24:49.955674

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '0a719c530811'
down_revision = 'b9f1fe4473a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
