"""empty message

Revision ID: 15678eb21c5e
Revises: d350b62f2cda
Create Date: 2018-05-25 17:19:22.008430

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '15678eb21c5e'
down_revision = 'd350b62f2cda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_channel', sa.Column('default_channel',
                                              sa.Boolean(),
                                              nullable=False,
                                              server_default='0'
                                              ))
    op.add_column('source_channel', sa.Column(
        'default_color', sa.String(length=1), nullable=True))
    op.alter_column('source_channel', 'name',
                    existing_type=sa.VARCHAR(length=50),
                    nullable=False)
    op.drop_column('volume', 'size')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('volume', sa.Column('size', sa.INTEGER(),
                                      autoincrement=False, nullable=True))
    op.alter_column('source_channel', 'name',
                    existing_type=sa.VARCHAR(length=50),
                    nullable=True)
    op.drop_column('source_channel', 'default_color')
    op.drop_column('source_channel', 'default_channel')
    # ### end Alembic commands ###
