"""empty message

Revision ID: 1798e1660751
Revises: 7d864727c13b
Create Date: 2018-05-27 11:58:26.646787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1798e1660751'
down_revision = '7d864727c13b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_channel', sa.Column('type', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_channel', 'type')
    # ### end Alembic commands ###
