"""empty message

Revision ID: 27a85dd33e40
Revises: 5e2eceb58ee7
Create Date: 2018-05-28 07:42:26.179084

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '27a85dd33e40'
down_revision = '5e2eceb58ee7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bioobject', sa.Column('areas', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGONZ', srid=4566, dimension=3, management=True, use_typmod=False), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bioobject', 'areas')
    # ### end Alembic commands ###
