"""empty message

Revision ID: 44d436f46d0c
Revises: c74007bd9007
Create Date: 2018-05-28 03:53:48.345670

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '44d436f46d0c'
down_revision = 'c74007bd9007'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_bioobject_areas', table_name='bioobject')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_bioobject_areas', 'bioobject', ['areas'], unique=False)
    # ### end Alembic commands ###
