"""empty message

Revision ID: 54bfaf2ff871
Revises: e9bb29ac1bf2
Create Date: 2018-05-29 15:47:24.245518

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '54bfaf2ff871'
down_revision = 'e9bb29ac1bf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bioobject', sa.Column('areas', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGONZ', srid=4566, dimension=3, management=True, use_typmod=False), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bioobject', 'areas')
    # ### end Alembic commands ###
