"""empty message

Revision ID: 5a2f3590764c
Revises: 
Create Date: 2018-05-29 15:01:04.554254

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '5a2f3590764c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('idx_bioobject_areas', table_name='bioobject')
    # ### end Alembic commands ###


def downgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index('idx_bioobject_areas', 'bioobject', ['areas'], unique=False)
    # ### end Alembic commands ###
