"""empty message

Revision ID: 5b5c993cc5d7
Revises: 15678eb21c5e
Create Date: 2018-05-25 17:28:42.287060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b5c993cc5d7'
down_revision = '15678eb21c5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
