"""empty message

Revision ID: 6eeb12db17b7
Revises: 0977995af177
Create Date: 2018-05-28 07:35:16.034200

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '6eeb12db17b7'
down_revision = '0977995af177'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bioobject', 'areas')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bioobject', sa.Column('areas', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4566), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
