"""empty message

Revision ID: 7d864727c13b
Revises: b6b8fc01ce50
Create Date: 2018-05-26 06:45:17.855193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d864727c13b'
down_revision = 'b6b8fc01ce50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('links')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links',
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('volume_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('link', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['volume_id'], ['volume.id'], name='links_volume_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='links_pkey')
    )
    # ### end Alembic commands ###
