"""empty message

Revision ID: 84b8274834f8
Revises: 27a85dd33e40
Create Date: 2018-05-29 08:19:40.404542

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '84b8274834f8'
down_revision = '27a85dd33e40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
