"""empty message

Revision ID: 9f6f3abbe2e3
Revises: 54bfaf2ff871
Create Date: 2018-05-29 16:42:38.935682

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '9f6f3abbe2e3'
down_revision = '54bfaf2ff871'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
