"""empty message

Revision ID: a7a61868e63b
Revises: 
Create Date: 2018-06-06 13:38:40.084566

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a7a61868e63b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.add_column('bioobjectcollection', sa.Column('link_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bioobjectcollection', 'link', ['link_id'], ['id'])
    op.alter_column('rating', 'classificationtype_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('rating', 'object_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('rating', 'rating_source_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rating', 'rating_source_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('rating', 'object_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('rating', 'classificationtype_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'bioobjectcollection', type_='foreignkey')
    op.drop_column('bioobjectcollection', 'link_id')
    op.create_table('users',
    sa.Column('user_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    # ### end Alembic commands ###
