"""empty message

Revision ID: b6b8fc01ce50
Revises: f878dc26bf08
Create Date: 2018-05-26 06:40:09.854780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6b8fc01ce50'
down_revision = 'f878dc26bf08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
