"""empty message

Revision ID: b9aa86b73fb1
Revises: 9f6f3abbe2e3
Create Date: 2018-05-29 17:14:26.044588

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'b9aa86b73fb1'
down_revision = '9f6f3abbe2e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
