"""empty message

Revision ID: c0b24dc6550c
Revises: 6eeb12db17b7
Create Date: 2018-05-28 07:35:31.382391

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'c0b24dc6550c'
down_revision = '6eeb12db17b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bioobject', sa.Column('areas', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4566, dimension=3, management=True, use_typmod=False), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bioobject', 'areas')
    # ### end Alembic commands ###
