"""empty message

Revision ID: c49d5736f72a
Revises: f9f7c37d858c
Create Date: 2018-05-30 13:45:40.850152

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c49d5736f72a'
down_revision = 'f9f7c37d858c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.alter_column('ratingsource', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('ratingsource_user_id_fkey', 'ratingsource', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('ratingsource_user_id_fkey', 'ratingsource', 'users', ['user_id'], ['id'])
    op.alter_column('ratingsource', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table('users',
    sa.Column('user_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    # ### end Alembic commands ###
