"""empty message

Revision ID: c74007bd9007
Revises: 1798e1660751
Create Date: 2018-05-27 13:43:52.334012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c74007bd9007'
down_revision = '1798e1660751'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('source_channel')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_channel',
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('volume_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('source_url', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('default_channel', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('default_color', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['volume_id'], ['volume.id'], name='source_channel_volume_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='source_channel_pkey')
    )
    # ### end Alembic commands ###
