"""empty message

Revision ID: d350b62f2cda
Revises: b4e7fc7c51b5
Create Date: 2018-05-25 11:58:21.590072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd350b62f2cda'
down_revision = 'b4e7fc7c51b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('volume', sa.Column('dataset_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'volume', 'data_set', ['dataset_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'volume', type_='foreignkey')
    op.drop_column('volume', 'dataset_id')
    # ### end Alembic commands ###
