"""empty message

Revision ID: e8d3e4624423
Revises: 84b8274834f8
Create Date: 2018-05-29 08:21:02.552017

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'e8d3e4624423'
down_revision = '84b8274834f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
