"""empty message

Revision ID: e9bb29ac1bf2
Revises: 5a2f3590764c
Create Date: 2018-05-29 15:46:40.349135

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'e9bb29ac1bf2'
down_revision = '5a2f3590764c'
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('bioobject', 'areas')
    # ### end Alembic commands ###


def downgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('bioobject', sa.Column('areas', geoalchemy2.types.Geometry(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
