"""empty message

Revision ID: f878dc26bf08
Revises: 5b5c993cc5d7
Create Date: 2018-05-25 17:29:02.445836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f878dc26bf08'
down_revision = '5b5c993cc5d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
