"""empty message

Revision ID: f9659ed7b365
Revises: c0b24dc6550c
Create Date: 2018-05-28 07:41:00.774459

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'f9659ed7b365'
down_revision = 'c0b24dc6550c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
