"""empty message

Revision ID: fbc774994fe4
Revises: e8d3e4624423
Create Date: 2018-05-29 08:21:51.749553

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'fbc774994fe4'
down_revision = 'e8d3e4624423'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
